import { typeBuilder } from 'shared/TypeHelper';

export default typeBuilder([
  'WEATHERSTATIONS_REQUEST',
  'WEATHERSTATIONS_SUCCESS',
  'WEATHERSTATIONS_ERROR',
  'WEATHERSTATION_SELECTED',
  'ACTUALWEATHER_REQUEST',
  'ACTUALWEATHER_SUCCESS',
  'ACTUALWEATHER_ERROR'
]);
