const actionTypes = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  SUM: 'SUM',
  DATA_REQUEST: 'DATA_REQUEST',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_ERROR: 'DATA_ERROR',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  REMOVE_PRODUCT: 'PRODUCT',
  PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
  PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
  PRODUCT_DETAIL_ERROR: 'PRODUCT_DETAIL_ERROR'
};

export default actionTypes;
